### ISSUE TITLE
SIDD dataset is not avaiable

### ISSUE THREAD

**Issue by simpler66** [AbdoKamel/simple-camera-pipeline#17]
Hi, I want to download the rawRGB dataset (both train set and val set). However, the SIDD dataset is not avaiable at https://www.eecs.yorku.ca/~kamel/sidd/dataset.php. If someone could offer the new url to download it, or share a download link of baidunetdisk. thanks~

**Comment by rachelconn** [comment]
Why did you close this issue? I used to be able to access the dataset via FTP but it seems to not work anymore. Did you find a way to access it, or give up?
