### ISSUE TITLE
if is there a error in demo.m

### ISSUE THREAD

**Issue by GuideWsp** [AbdoKamel/simple-camera-pipeline#2]
normalizedRawFilename = '0001_GT_RAW_010.MAT';
metadataFilename = '0001_METADATA_RAW_010.MAT';
imNormRaw = load(fullfile('data', normalizedRawFilename));
imNormRaw = imNormRaw.x;
metadata = load(fullfile('data', metadataFilename));
metadata = metadata.metadata;
imSrgb2 = run_pipeline(imRaw, metadata, 'raw', 'srgb');
imwrite(imSrgb2, fullfile('data', [normalizedRawFilename, '_sRGB.png']));

Maybe the imRaw shoud be imNormRaw?
but when i replace imRaw by imNormRaw, the result is not right.
so will you tell me how to use imNormRaw and metadata produce imSrgb?
thanks.

**Comment by AbdoKamel** [comment]
This line:
imSrgb2 = run_pipeline(imRaw, metadata, 'raw', 'srgb');
Should be:
imSrgb2 = run_pipeline(imNormRaw, metadata, 'normal', 'srgb');
